### ISSUE TITLE
TypeError: Cannot read property 'geometry' of undefined

### ISSUE THREAD

**Issue by miguelcobain** [marcelreppi/shape2geohash#2]
Running this results in a `TypeError: Cannot read property 'geometry' of undefined` error.

```js
const shape2geohash = require('shape2geohash');

await shape2geohash({
    type: 'Feature',
    geometry: {
        type: 'LineString',
        coordinates: [
            [-8.49468397061034,41.1146472476304],
            [-8.49468566805409,41.1146850333377]
        ]
    }
});
```

**Comment by marcelreppi** [comment]
Thank you very much for submitting the issue!
I am very sorry I only get back to it so late, I did not get a notification that there was an issue!
I have just fixed it and updated the package to version 1.2.4.
